name: bcc
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib
  - seaborn
  - numpy==1.23.5
  - scanpy
  - scipy
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch-lightning
  - pytest
  - pyarrow
  - pre-commit
  - scikit-learn
  - scikit-image
  - tensorboard
  - torchmetrics
  - psutil
  - submitit
  - pandas
  - pytest
  - python-igraph
  - pytest-flake8
  - leidenalg
  - jupyter
  - jupytext
  - pip:
      - scarches
steps:
  - uses: actions/checkout@v3
